### PR TITLE
fix docs for https://github.com/kisslinux/kiss-init/issues/1

### PR DESCRIPTION
**Pull request by a-schaefers**
Hope this helps. Feel free to rearrange or reword it, or come up with something altogether different-- i just want to do something about this at least.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Thanks. It might be worth also linking to this page (https://wiki.archlinux.org/index.php/fstab) to provide information about creating your own `fstab`. :+1:

**Comment by a-schaefers** [comment]
Nice

**Comment by dylanaraps** [comment]
Thanks :)

**Comment by a-schaefers** [comment]
HOAH take another check that was close

**Comment by a-schaefers** [comment]
I pushed right as you were merging

**Comment by dylanaraps** [comment]
Hah. That was close.

**Comment by a-schaefers** [comment]
@dylanaraps  it looks bad, needs fixed also root=root typo. I will leave the rest up to you.

**Comment by dylanaraps** [comment]
Willl fix it. :+1:

**Pull request merged**
